# Generated by Django 4.2.2 on 2023-07-06 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=255)),
                ('Description', models.TextField(max_length=450)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='open', max_length=255)),
                ('document_path', models.FileField(upload_to='tender_documents/')),
                ('legalized_documents', models.FileField(upload_to='legalized_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('campony', models.CharField(max_length=255, null=True)),
                ('catagory', models.CharField(choices=[('Type 1', 'Construction'), ('Type 2', 'Telecomunication'), ('Type 3', 'Software products')], max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('winner', 'Winner'), ('loose', 'Failed'), ('pending', 'Pending')], default='Pending', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('document_path', models.FileField(upload_to='bid_documents/')),
                ('tender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='E_Tender.tender')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
