# Generated by Django 4.2.2 on 2023-07-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Tender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='catagory',
            field=models.CharField(choices=[('Construction', 'Construction'), ('Telecomunication', 'Telecomunication'), ('Software products', 'Software products')], max_length=255),
        ),
    ]
